name: BankCredit
version: 0.8.5
authors: [B1GSt4R]
website: https://blockstone.de
main: blockstone.B1GSt4R.BankCredit.Main.system
softdepend: [Vault, TimeRank]
commands:
  Bank:
    usage: </command>
    description: test economy
    aliases: [Kredit, Credit, kredit, credit, bank]
  BankCredit:
    usage: </command>
    description: check for Update
  inactive:
    usage: </command>
    description: coming soon
  tc:
    usage: </command>
    description: Transfer Player Credit to anthoer player
    aliases: [transfer,credittransfer,transfercredit,ct]