name: BankCredit
version: 0.5.2
authors: [B1GSt4R]
website: https://blockstone.de
main: blockstone.B1GSt4R.BankCredit.Main.system
softdepend: [Vault]
commands:
  Bank:
    usage: </command>
    description: test economy
    aliases: [Kredit, Credit, kredit, credit, bank]